// <auto-generated />
using System;
using AgileTeamsData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgileTeamsData.Migrations
{
    [DbContext(typeof(AgileTeamsContext))]
    [Migration("20201212070840_updatedModels13")]
    partial class updatedModels13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgileTeamsData.Data.Project", b =>
                {
                    b.Property<string>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("Date");

                    b.Property<string>("Description");

                    b.Property<string>("ProjectName");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AgileTeamsData.Data.WorkItemPriority", b =>
                {
                    b.Property<int>("PriorityID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PriorityName")
                        .IsRequired();

                    b.HasKey("PriorityID");

                    b.ToTable("WorkItemPriorities");
                });

            modelBuilder.Entity("AgileTeamsData.Data.WorkItemType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .IsRequired();

                    b.HasKey("TypeID");

                    b.ToTable("WorkItemTypes");
                });

            modelBuilder.Entity("AgileTeamsData.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("State");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("AgileTeamsData.Models.ApplicationUserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleId");

                    b.Property<string>("RoleName");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUserRoles");
                });

            modelBuilder.Entity("AgileTeamsData.Models.ProjectTaskStatusLog", b =>
                {
                    b.Property<string>("ProjectTaskStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LogDate");

                    b.Property<int?>("StatusID");

                    b.Property<string>("TicketID");

                    b.Property<string>("UserId");

                    b.HasKey("ProjectTaskStatusId");

                    b.HasIndex("StatusID");

                    b.HasIndex("TicketID");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectTaskStatusLogs");
                });

            modelBuilder.Entity("AgileTeamsData.Models.Ticket", b =>
                {
                    b.Property<string>("TicketID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("Date");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("Date");

                    b.Property<string>("TicketDescription")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TicketName")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TicketOwnerID");

                    b.Property<int>("TicketStatusID");

                    b.Property<int>("TicketTypeID");

                    b.Property<string>("TicketWorkItemID");

                    b.HasKey("TicketID");

                    b.HasIndex("TicketOwnerID");

                    b.HasIndex("TicketStatusID");

                    b.HasIndex("TicketTypeID");

                    b.HasIndex("TicketWorkItemID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("AgileTeamsData.Models.TicketStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName")
                        .IsRequired();

                    b.HasKey("StatusID");

                    b.ToTable("TicketStatuses");
                });

            modelBuilder.Entity("AgileTeamsData.Models.TicketType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .IsRequired();

                    b.HasKey("TypeID");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("AgileTeamsData.Models.WorkItem", b =>
                {
                    b.Property<string>("WorkItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("Date");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("Date");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("TargetEndDate")
                        .HasColumnType("Date");

                    b.Property<string>("WorkItemDescription")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("WorkItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("WorkItemOwnerID");

                    b.Property<int>("WorkItemPriorityID");

                    b.Property<string>("WorkItemProjectID");

                    b.Property<int>("WorkItemStatusID");

                    b.Property<int>("WorkItemTypeID");

                    b.HasKey("WorkItemID");

                    b.HasIndex("WorkItemOwnerID");

                    b.HasIndex("WorkItemPriorityID");

                    b.HasIndex("WorkItemProjectID");

                    b.HasIndex("WorkItemStatusID");

                    b.HasIndex("WorkItemTypeID");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("AgileTeamsData.Models.WorkItemComment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CommentWorkItemID");

                    b.Property<string>("SubmittedBy");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("Date");

                    b.Property<string>("TicketID");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("Date");

                    b.HasKey("CommentID");

                    b.HasIndex("CommentWorkItemID");

                    b.HasIndex("TicketID");

                    b.ToTable("WorkItemComments");
                });

            modelBuilder.Entity("AgileTeamsData.Models.WorkItemStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName")
                        .IsRequired();

                    b.HasKey("StatusID");

                    b.ToTable("WorkItemStatuses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AgileTeamsData.Models.ProjectTaskStatusLog", b =>
                {
                    b.HasOne("AgileTeamsData.Models.TicketStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID");

                    b.HasOne("AgileTeamsData.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketID");

                    b.HasOne("AgileTeamsData.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AgileTeamsData.Models.Ticket", b =>
                {
                    b.HasOne("AgileTeamsData.Models.ApplicationUser", "TicketOwner")
                        .WithMany()
                        .HasForeignKey("TicketOwnerID");

                    b.HasOne("AgileTeamsData.Models.TicketStatus", "TicketStatus")
                        .WithMany()
                        .HasForeignKey("TicketStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgileTeamsData.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgileTeamsData.Models.WorkItem", "TicketWorkItem")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketWorkItemID");
                });

            modelBuilder.Entity("AgileTeamsData.Models.WorkItem", b =>
                {
                    b.HasOne("AgileTeamsData.Models.ApplicationUser", "WorkItemOwner")
                        .WithMany()
                        .HasForeignKey("WorkItemOwnerID");

                    b.HasOne("AgileTeamsData.Data.WorkItemPriority", "WorkItemPriority")
                        .WithMany()
                        .HasForeignKey("WorkItemPriorityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgileTeamsData.Data.Project", "Project")
                        .WithMany("WorkItems")
                        .HasForeignKey("WorkItemProjectID");

                    b.HasOne("AgileTeamsData.Models.WorkItemStatus", "WorkItemStatus")
                        .WithMany()
                        .HasForeignKey("WorkItemStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgileTeamsData.Data.WorkItemType", "WorkItemType")
                        .WithMany()
                        .HasForeignKey("WorkItemTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgileTeamsData.Models.WorkItemComment", b =>
                {
                    b.HasOne("AgileTeamsData.Models.WorkItem", "WorkItem")
                        .WithMany("Comments")
                        .HasForeignKey("CommentWorkItemID");

                    b.HasOne("AgileTeamsData.Models.Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketID");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AgileTeamsData.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgileTeamsData.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgileTeamsData.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AgileTeamsData.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
